# Generated by Django 4.2.30 on 2026-07-06 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('Kanzu / Thobe', 'Kanzu / Thobe'), ('Abaya', 'Abaya'), ('Hijab / Scarf', 'Hijab / Scarf'), ('Jalabiya', 'Jalabiya'), ('Prayer Wear', 'Prayer Wear'), ("Men's Accessories", "Men's Accessories"), ('Kids', 'Kids'), ('Shoes', 'Shoes'), ('Other', 'Other')], default='Kanzu / Thobe', max_length=40)),
                ('size', models.CharField(choices=[('General', [('-', '-'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('Free size', 'Free size')]), ('Kids thobe (height)', [('20', '20'), ('22', '22'), ('24', '24'), ('26', '26'), ('28', '28'), ('30', '30'), ('32', '32'), ('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('42', '42'), ('44', '44'), ('46', '46'), ('48', '48'), ('50', '50'), ('52', '52')]), ('Men thobe (height-width)', [('54-20', '54-20'), ('54-21', '54-21'), ('54-22', '54-22'), ('54-23', '54-23'), ('54-24', '54-24'), ('54-26', '54-26'), ('55-20', '55-20'), ('55-21', '55-21'), ('55-22', '55-22'), ('56-20', '56-20'), ('56-21', '56-21'), ('56-22', '56-22'), ('56-23', '56-23'), ('56-24', '56-24'), ('57-20', '57-20'), ('57-21', '57-21'), ('57-22', '57-22'), ('57-23', '57-23'), ('57-24', '57-24'), ('58-20', '58-20'), ('58-21', '58-21'), ('58-22', '58-22'), ('58-23', '58-23'), ('58-24', '58-24'), ('58-25', '58-25'), ('58-26', '58-26'), ('59-20', '59-20'), ('59-21', '59-21'), ('59-22', '59-22'), ('59-23', '59-23'), ('59-24', '59-24'), ('60-20', '60-20'), ('60-22', '60-22'), ('60-23', '60-23'), ('60-24', '60-24'), ('60-26', '60-26'), ('60-28', '60-28'), ('62-22', '62-22'), ('62-23', '62-23'), ('62-24', '62-24'), ('62-26', '62-26'), ('62-28', '62-28')]), ('Shoes', [('Shoe 40', 'Shoe 40'), ('Shoe 41', 'Shoe 41'), ('Shoe 42', 'Shoe 42'), ('Shoe 43', 'Shoe 43'), ('Shoe 44', 'Shoe 44'), ('Shoe 45', 'Shoe 45'), ('Shoe 46', 'Shoe 46')])], default='-', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (KSh)')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('low_at', models.PositiveIntegerField(default=3, verbose_name='Alert when stock is at or below')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', 'size'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_snapshot', models.CharField(max_length=160)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='shop.product')),
                ('sold_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
